name: code_check
on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn
      - run: yarn type-check
      - run: yarn format:check
      - run: yarn lint
      - run: yarn test
